name: Update Cignal EPG

on:
  schedule:
    - cron: '0 2 * * *'   # Daily at 2:00 AM UTC
  workflow_dispatch:

jobs:
  update-epg:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # 🔑 Required for GITHUB_TOKEN to push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run EPG fetcher
        run: python epg_fetcher.py

      - name: Commit and push if changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add cignal_epg.xml
          git diff --staged --quiet || git commit -m "Update EPG data"
          git push --force
