name: Update Cignal EPG

on:
  schedule:
    - cron: '0 2 * * *'   # Run daily at 2:00 AM UTC
  workflow_dispatch:       # Allow manual trigger via GitHub UI

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run EPG fetcher
        run: python epg_fetcher.py

      - name: Commit and push if changes
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.CIGNAL_EPG }}@github.com/Alobadman/Cignal_EPG.git
          git add cignal_epg.xml
          git diff --staged --quiet || git commit -m "Update EPG data"
          git push --force
